name: Build and Deploy Vite App to Pages

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          # We point the cache to the package-lock inside the client folder
          cache-dependency-path: ./client/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ./client

      - name: Build production site
        run: npm run build
        working-directory: ./client

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload compiled artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Vite outputs compiled code to a folder named 'dist' inside the working directory
          path: './client/dist/'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
